2023-08-22 11:25:01,890 - 890.5482292175293 - create_pool - ERROR - При подключении к базе данных произошло исключение: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)
2023-08-22 11:25:01,892 - 892.5020694732666 - create_pool - ERROR - При подключении к базе данных произошло исключение: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)
2023-08-22 11:25:51,022 - 22.974252700805664 - create_pool - ERROR - При подключении к базе данных произошло исключение: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)
2023-08-22 11:25:51,024 - 24.58930015563965 - create_pool - ERROR - При подключении к базе данных произошло исключение: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)
2023-08-22 11:30:32,251 - 251.47700309753418 - create_pool - ERROR - При подключении к базе данных произошло исключение: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)
2023-08-22 11:30:32,253 - 253.0825138092041 - create_pool - ERROR - При подключении к базе данных произошло исключение: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)
2023-08-22 11:30:37,846 - 846.6973304748535 - backup_bd_pss - ERROR - Произошла ошибка при попытке снятия дампа базы данных: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)
2023-08-22 11:31:26,152 - 152.8952121734619 - create_pool - ERROR - При подключении к базе данных произошло исключение: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)
2023-08-22 11:31:26,154 - 154.3598175048828 - create_pool - ERROR - При подключении к базе данных произошло исключение: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)
2023-08-22 11:31:27,677 - 677.556037902832 - backup_bd_pss - ERROR - Произошла ошибка при попытке снятия дампа базы данных: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)
2023-08-22 11:32:27,316 - 316.38073921203613 - backup_bd_pss - ERROR - Произошла ошибка при попытке снятия дампа базы данных: ошибка синтаксиса (примерное положение: "pg_dump")
